// E-Setu One-Time Database Seed Data
// This is the server-side source of truth used to populate the SQLite database
// the FIRST time it is created. After that, the database (not this file) is authoritative.
//
// No fake people/companies are seeded (kabadiwalas, recyclers, lots, sales history all
// start genuinely empty) — only real reference data (material categories, market rates,
// safety guidance) is pre-loaded, since that represents domain knowledge, not fake entities.
// Real dealers and recyclers only appear here once they register themselves through the app.

const SEED_DATA = {
  validCpcbRegistrations: [],
  predefinedRecyclers: [],
  predefinedKabadiwalas: [],

  materials: [
    {
      id: 'mat-pcb-high', symbol: 'PCB-HI', name: 'High-Grade PCBs (Server / Smartphone / RAM)',
      nameMr: 'उच्च दर्जाचे पीसीबी (सर्व्हर / स्मार्टफोन / रॅम)',
      nameHi: 'उच्च गुणवत्ता पीसीबी (सर्वर / स्मार्टफोन / रैम)',
      nameTa: 'உயர்தர பிசிபி பலகைகள் (சர்வர் / ஸ்மார்ட்போன் / ரேம்)',
      nameTe: 'హై-గ్రేడ్ పిసిబి బోర్డులు (సర్వర్ / స్మార్ట్‌ఫోన్ / ర్యామ్)',
      nameKn: 'ಉನ್ನತ ದರ್ಜೆಯ ಪಿಸಿಬಿ ಬೋರ್ಡ್‌ಗಳು (ಸರ್ವರ್ / ಸ್ಮಾರ್ಟ್‌ಫೋನ್)',
      nameMl: 'ഹൈ-ഗ്രേഡ് പിസിബി ബോർഡുകൾ (സെർവർ / സ്മാർട്ട്ഫോൺ)',
      icon: '💻', customerRate: 950, recyclerRate: 1280, rate6hrAgo: 1220, recyclerRate6hrAgo: 1220, unit: 'kg',
      changePct: '+4.9%', isPositive: true, dayHigh: 1310, dayLow: 1210, volume: '1,420 kg',
      sparkline: [1210, 1225, 1220, 1240, 1255, 1250, 1270, 1265, 1275, 1280],
      description: 'Telecom boards, gold-plated server motherboards, multi-layer circuit boards.',
      metals: 'Gold (0.25g/kg), Silver (1.2g/kg), Copper (18%), Palladium',
      hazardLevel: 'Medium',
      properProcess: 'Hydrometallurgical chemical extraction in closed loop (Never acid leach at home!)'
    },
    {
      id: 'mat-copper-wire', symbol: 'CU-WIRE', name: 'Copper Cables & Insulated Wiring',
      nameMr: 'तांब्याची वायर आणि केबल्स', nameHi: 'तांबे की तार और केबल',
      nameTa: 'தாமிர கம்பிகள் மற்றும் கேபிள்கள்', nameTe: 'రాగి వైర్లు మరియు కేబుల్స్',
      nameKn: 'ತಾಮ್ರದ ತಂತಿಗಳು ಮತ್ತು ಕೇಬಲ್‌ಗಳು', nameMl: 'ചെമ്പ് വയറുകളും കേബിളുകളും',
      icon: '🔌', customerRate: 360, recyclerRate: 485, rate6hrAgo: 460, recyclerRate6hrAgo: 460, unit: 'kg',
      changePct: '+5.4%', isPositive: true, dayHigh: 495, dayLow: 450, volume: '4,800 kg',
      sparkline: [450, 455, 462, 460, 470, 468, 475, 480, 482, 485],
      description: 'Power cables, network cables, appliance wiring with PVC sheath.',
      metals: 'Copper (45-65% by weight), PVC/PE plastic',
      hazardLevel: 'High',
      properProcess: 'Mechanical wire stripping/granulation (Never burn in open air - creates cancer-causing dioxins!)'
    },
    {
      id: 'mat-li-battery', symbol: 'LI-BATT', name: 'Lithium-Ion / EV / Laptop Batteries',
      nameMr: 'लिथियम-आयन / लॅपटॉप बॅटऱ्या', nameHi: 'लिथियम-आयन / लैपटॉप बैटरी',
      nameTa: 'லித்தியம்-அயன் / மடிக்கணினி பேட்டரிகள்', nameTe: 'లిథియం-అయాన్ / ల్యాప్‌టాప్ బ్యాటరీలు',
      nameKn: 'ಲಿಥಿಯಂ-ಐಯಾನ್ / ಲ್ಯಾಪ್‌ಟಾಪ್ ಬ್ಯಾಟರಿಗಳು', nameMl: 'ലിഥിയം-അയൺ / ലാപ്ടോപ്പ് ബാറ്ററികൾ',
      icon: '🔋', customerRate: 160, recyclerRate: 225, rate6hrAgo: 235, recyclerRate6hrAgo: 235, unit: 'kg',
      changePct: '-4.2%', isPositive: false, dayHigh: 240, dayLow: 218, volume: '850 kg',
      sparkline: [238, 235, 232, 230, 226, 224, 228, 222, 224, 225],
      description: 'Mobile phone pouch cells, 18650 laptop cylinders, EV battery packs.',
      metals: 'Cobalt (15%), Lithium (7%), Nickel, Graphite',
      hazardLevel: 'Critical',
      properProcess: 'Inert atmosphere shredding & black mass recovery (Never puncture or throw in water - explosive fire!)'
    },
    {
      id: 'mat-crt-monitors', symbol: 'CRT-GLS', name: 'CRT Televisions & Old Monitor Glass',
      nameMr: 'जुने सीआरटी टीव्ही आणि मॉनिटर', nameHi: 'पुराने सीआरटी टीवी और मॉनिटर',
      nameTa: 'பழைய சிஆர்டி டிவி மற்றும் மானிட்டர் கண்ணாடி', nameTe: 'పాత సిఆర్టి టివి మరియు మానిటర్ గ్లాస్',
      nameKn: 'ಹಳೆಯ ಸಿಆರ್‌ಟಿ ಟಿವಿ ಮತ್ತು ಮಾನಿಟರ್ ಗಾಜು', nameMl: 'പഴയ സിആർടി ടിവി, മോണിറ്റർ ഗ്ലാസ്',
      icon: '📺', customerRate: 15, recyclerRate: 28, rate6hrAgo: 28, recyclerRate6hrAgo: 28, unit: 'kg',
      changePct: '0.0%', isPositive: true, dayHigh: 31, dayLow: 25, volume: '6,200 kg',
      sparkline: [27, 28, 26, 28, 29, 28, 27, 28, 29, 28],
      description: 'Heavy picture tube glass with lead funnel and phosphor faceplate.',
      metals: 'Lead (up to 2 kg per tube), Glass cullet, Copper deflection yoke',
      hazardLevel: 'High',
      properProcess: 'Lead smelting furnace under negative pressure (Implosion hazard if smashed!)'
    },
    {
      id: 'mat-lcd-led', symbol: 'LCD-SCR', name: 'LCD / LED Display Panels & Monitors',
      nameMr: 'एलसीडी / एलईडी डिस्प्ले स्क्रीन', nameHi: 'एलसीडी / एलईडी डिस्प्ले स्क्रीन',
      nameTa: 'எல்சிடி / எல்இடி திரை பேனல்கள்', nameTe: 'ఎల్‌సిడి / ఎల్‌ఇడి డిస్‌ప్లే ప్యానెల్లు',
      nameKn: 'ಎಲ್‌ಸಿಡಿ / ಎಲ್‌ಇಡಿ ಡಿಸ್ಪ್ಲೇ ಪ್ಯಾನೆಲ್‌ಗಳು', nameMl: 'എൽസിഡി / എൽഇഡി ഡിസ്പ്ലേ പാനലുകൾ',
      icon: '🖥️', customerRate: 85, recyclerRate: 120, rate6hrAgo: 112, recyclerRate6hrAgo: 112, unit: 'kg',
      changePct: '+7.1%', isPositive: true, dayHigh: 126, dayLow: 108, volume: '1,950 kg',
      sparkline: [110, 112, 114, 113, 116, 118, 117, 119, 121, 120],
      description: 'Flat screen monitors, TV panels, CCFL or LED backlights.',
      metals: 'Indium Tin Oxide, Aluminum frame, Optical diffusers',
      hazardLevel: 'Medium',
      properProcess: 'Careful demanufacturing to safely isolate mercury backlights (if CCFL).'
    },
    {
      id: 'mat-electric-motors', symbol: 'MOT-MAG', name: 'Electric Motors & Neodymium Magnets',
      nameMr: 'इलेक्ट्रिक मोटर्स आणि चुंबक संच', nameHi: 'इलेक्ट्रिक मोटर और चुंबक असेंबली',
      nameTa: 'மின்சார மோட்டார்கள் மற்றும் காந்தங்கள்', nameTe: 'ఎలక్ట్రిక్ మోటార్లు మరియు అయస్కాంతాలు',
      nameKn: 'ವಿದ್ಯುತ್ ಮೋಟಾರ್‌ಗಳು ಮತ್ತು ಆಯಸ್ಕಾಂತಗಳು', nameMl: 'ഇലക്ട്രിക് മോട്ടോറുകളും കാന്തങ്ങളും',
      icon: '⚙️', customerRate: 110, recyclerRate: 165, rate6hrAgo: 158, recyclerRate6hrAgo: 158, unit: 'kg',
      changePct: '+4.4%', isPositive: true, dayHigh: 172, dayLow: 152, volume: '3,100 kg',
      sparkline: [154, 156, 158, 160, 159, 162, 161, 163, 166, 165],
      description: 'Hard drive voice coil motors, fan motors, compressor stators.',
      metals: 'Neodymium (Rare Earth NdFeB), Pure Copper windings, Steel armature',
      hazardLevel: 'Low',
      properProcess: 'Automated demagnetization & rare earth alloy recycling.'
    },
    {
      id: 'mat-e-plastics', symbol: 'PLAS-MIX', name: 'Flame Retardant E-Waste Plastics',
      nameMr: 'इलेक्ट्रॉनिक प्लास्टिक (ABS/PC)', nameHi: 'इलेक्ट्रॉनिक प्लास्टिक (ABS/PC)',
      nameTa: 'மின்னணு பிளாஸ்டிக் கழிவுகள்', nameTe: 'ఎలక్ట్రానిక్ ప్లాస్టిక్ వ్యర్థాలు',
      nameKn: 'ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಪ್ಲಾಸ್ಟಿಕ್ ತ್ಯಾಜ್ಯ', nameMl: 'ഇലക്ട്രോണിക് പ്ലാസ്റ്റിക് മാലിന്യങ്ങൾ',
      icon: '♻️', customerRate: 22, recyclerRate: 38, rate6hrAgo: 38, recyclerRate6hrAgo: 38, unit: 'kg',
      changePct: '0.0%', isPositive: true, dayHigh: 41, dayLow: 35, volume: '9,400 kg',
      sparkline: [36, 37, 38, 37, 39, 38, 37, 38, 39, 38],
      description: 'Printer bodies, monitor bezels, keyboard keys (ABS, HIPS, PC).',
      metals: 'Engineering polymers for industrial re-granulation',
      hazardLevel: 'Medium',
      properProcess: 'Near-infrared optical sorting (Never melt in cookpots - toxic bromine gases!)'
    }
  ],

  dailyCollectionHistory: [],
  customerSalesHistory: [],
  customerSalesSummary: {
    totalWeightSoldKg: 0, totalCashReceived: 0, totalPickupsCompleted: 0,
    totalTreesEquivalent: 0, totalCo2PreventedKg: 0, toxicHeavyMetalsDivertedKg: 0,
    preferredScrapDealer: ''
  },
  customerMonthlyComparison: [],

  kabadiwalas: [],
  recyclers: [],
  inventory: [],
  lots: [],

  // Illustrative estimated CO2-avoided-per-kg-recycled factors, by material id — approximate
  // figures in the range commonly cited for avoided-virgin-extraction emissions of each
  // material category (not a scientifically audited life-cycle assessment). Used only to
  // give the Environmental Tracker a real, internally-consistent number to compute from.
  co2FactorsByMaterialId: {
    'mat-pcb-high': 15,
    'mat-copper-wire': 4,
    'mat-li-battery': 6,
    'mat-crt-monitors': 1.5,
    'mat-lcd-led': 3,
    'mat-electric-motors': 5,
    'mat-e-plastics': 2
  },

  safetyGuides: [
    {
      id: 'safe-01', title: 'Danger: Never Burn Copper Wires in Open Air',
      titleMr: 'धोका: उघड्यावर तांब्याच्या तारा कधीही जाळू नका',
      titleHi: 'खतरा: खुली हवा में तांबे के तारों को कभी न जलाएं',
      titleTa: 'ஆபத்து: திறந்த வெளியில் தாமிர கம்பிகளை ஒருபோதும் எரிக்காதீர்கள்',
      titleTe: 'ప్రమాదం: బహిరంగ ప్రదేశంలో రాగి తీగలను ఎప్పుడూ కాల్చవద్దు',
      titleKn: 'ಅಪಾಯ: ಬಯಲಿನಲ್ಲಿ ತಾಮ್ರದ ತಂತಿಗಳನ್ನು ಎಂದಿಗೂ ಸುಡಬೇಡಿ',
      titleMl: 'അപകടം: തുറസ്സായ സ്ഥലത്ത് ചെമ്പ് വയറുകൾ ഒരിക്കലും കത്തിക്കരുത്',
      icon: '🚫🔥', color: '#dc2626',
      hazard: 'Toxic Dioxins & Black Furan Fumes',
      hazardHi: 'जहरीली डाइऑक्सिन और काला फ्यूरान धुआं',
      hazardMr: 'विषारी डायऑक्सिन आणि काळा फ्युरान धूर',
      hazardTa: 'நச்சு டையாக்சின் மற்றும் கருப்பு ஃபியூரான் புகை',
      hazardTe: 'విషపూరిత డయాక్సిన్‌లు మరియు నల్ల ఫ్యూరాన్ పొగ',
      hazardKn: 'ವಿಷಕಾರಿ ಡೈಆಕ್ಸಿನ್ ಮತ್ತು ಕಪ್ಪು ಫ್ಯೂರಾನ್ ಹೊಗೆ',
      hazardMl: 'വിഷലിപ്തമായ ഡയോക്സിനും കറുത്ത ഫ്യൂറാൻ പുകയും',
      healthRisk: 'Permanent lung damage, cancer risk, and lead poisoning for you and your family.',
      healthRiskHi: 'स्थायी फेफड़ों की क्षति, कैंसर का खतरा, और आपके व आपके परिवार के लिए सीसा विषाक्तता।',
      healthRiskMr: 'फुफ्फुसांचे कायमचे नुकसान, कर्करोगाचा धोका, आणि तुमच्यासाठी व कुटुंबासाठी शिशाची विषबाधा.',
      healthRiskTa: 'நுரையீரல் நிரந்தர சேதம், புற்றுநோய் அபாயம், மற்றும் உங்களுக்கும் உங்கள் குடும்பத்திற்கும் ஈய நச்சு.',
      healthRiskTe: 'మీకు మరియు మీ కుటుంబానికి శాశ్వత ఊపిరితిత్తుల నష్టం, క్యాన్సర్ ప్రమాదం, మరియు సీసం విషప్రయోగం.',
      healthRiskKn: 'ನಿಮಗೆ ಮತ್ತು ನಿಮ್ಮ ಕುಟುಂಬಕ್ಕೆ ಶಾಶ್ವತ ಶ್ವಾಸಕೋಶದ ಹಾನಿ, ಕ್ಯಾನ್ಸರ್ ಅಪಾಯ, ಮತ್ತು ಸೀಸದ ವಿಷಬಾಧೆ.',
      healthRiskMl: 'നിങ്ങൾക്കും കുടുംബത്തിനും ശാശ്വതമായ ശ്വാസകോശ തകരാർ, ക്യാൻസർ സാധ്യത, ഈയ വിഷബാധ.',
      safeMethod: 'Use simple manual mechanical wire strippers or sell directly to recyclers with plastic sheath intact. Recyclers pay for the plastic too!',
      safeMethodHi: 'साधारण हाथ से चलने वाले वायर स्ट्रिपर का उपयोग करें या प्लास्टिक कवर सहित सीधे रीसायकलर को बेचें। रीसायकलर प्लास्टिक के भी पैसे देते हैं!',
      safeMethodMr: 'साधे हाताने चालणारे वायर स्ट्रिपर वापरा किंवा प्लास्टिक आवरणासह थेट रिसायकलरला विका. रिसायकलर प्लास्टिकचेही पैसे देतात!',
      safeMethodTa: 'எளிய கை வயர் ஸ்ட்ரிப்பரைப் பயன்படுத்தவும் அல்லது பிளாஸ்டிக் உறையுடன் நேரடியாக மறுசுழற்சியாளரிடம் விற்கவும். மறுசுழற்சியாளர்கள் பிளாஸ்டிக்கிற்கும் பணம் தருவார்கள்!',
      safeMethodTe: 'సాధారణ చేతి వైర్ స్ట్రిప్పర్‌ను ఉపయోగించండి లేదా ప్లాస్టిక్ కవచంతో నేరుగా రీసైక్లర్‌కు అమ్మండి. రీసైక్లర్లు ప్లాస్టిక్‌కు కూడా డబ్బు చెల్లిస్తారు!',
      safeMethodKn: 'ಸರಳ ಕೈ ವೈರ್ ಸ್ಟ್ರಿಪ್ಪರ್ ಬಳಸಿ ಅಥವಾ ಪ್ಲಾಸ್ಟಿಕ್ ಹೊದಿಕೆಯೊಂದಿಗೆ ನೇರವಾಗಿ ಮರುಬಳಕೆದಾರರಿಗೆ ಮಾರಾಟ ಮಾಡಿ. ಮರುಬಳಕೆದಾರರು ಪ್ಲಾಸ್ಟಿಕ್‌ಗೂ ಹಣ ನೀಡುತ್ತಾರೆ!',
      safeMethodMl: 'ലളിതമായ കൈ വയർ സ്ട്രിപ്പർ ഉപയോഗിക്കുക അല്ലെങ്കിൽ പ്ലാസ്റ്റിക് ആവരണത്തോടെ നേരിട്ട് റീസൈക്ലറിന് വിൽക്കുക. റീസൈക്ലർമാർ പ്ലാസ്റ്റിക്കിനും പണം നൽകും!',
      audioScriptEn: 'Never burn insulated copper cables in the open. Burning PVC releases deadly dioxin gas causing cancer. Sell unstripped cables directly to authorized recyclers for full cash.',
      audioScriptMr: 'उघड्यावर तारा जाळल्याने कॅन्सर पसरवणारा विषारी धूर निघतो. तारा न जाळता थेट अधिकृत रिसायकलरला विका, ते प्लास्टिकचेही पैसे देतात!',
      audioScriptHi: 'खुली हवा में तारों को कभी न जलाएं! ऐसा करने से कैंसर पैदा करने वाला जहरीला धुआं निकलता है। पूरी केबल रीसायकलर को बेचें, वह सही दाम देगा।',
      audioScriptTa: 'திறந்த வெளியில் தாமிர கம்பிகளை ஒருபோதும் எரிக்காதீர்கள். PVC எரிப்பதால் புற்றுநோயை உண்டாக்கும் நச்சு டையாக்சின் வாயு வெளியேறும். கம்பிகளை உரிக்காமல் நேரடியாக அங்கீகரிக்கப்பட்ட மறுசுழற்சியாளரிடம் விற்று முழு பணம் பெறுங்கள்.',
      audioScriptTe: 'బహిరంగ ప్రదేశంలో ఇన్సులేటెడ్ రాగి కేబుళ్లను ఎప్పుడూ కాల్చవద్దు. PVC కాల్చడం వల్ల క్యాన్సర్‌కు కారణమయ్యే ప్రాణాంతక డయాక్సిన్ వాయువు విడుదలవుతుంది. కేబుళ్లను తీయకుండా నేరుగా అధీకృత రీసైక్లర్‌కు అమ్మి పూర్తి డబ్బు పొందండి.',
      audioScriptKn: 'ಬಯಲಿನಲ್ಲಿ ಇನ್ಸುಲೇಟೆಡ್ ತಾಮ್ರದ ಕೇಬಲ್‌ಗಳನ್ನು ಎಂದಿಗೂ ಸುಡಬೇಡಿ. PVC ಸುಡುವುದರಿಂದ ಕ್ಯಾನ್ಸರ್‌ಗೆ ಕಾರಣವಾಗುವ ಮಾರಣಾಂತಿಕ ಡೈಆಕ್ಸಿನ್ ಅನಿಲ ಬಿಡುಗಡೆಯಾಗುತ್ತದೆ. ಕೇಬಲ್‌ಗಳನ್ನು ಸುಲಿಯದೆ ನೇರವಾಗಿ ಅಧಿಕೃತ ಮರುಬಳಕೆದಾರರಿಗೆ ಮಾರಿ ಪೂರ್ಣ ಹಣ ಪಡೆಯಿರಿ.',
      audioScriptMl: 'തുറസ്സായ സ്ഥലത്ത് ഇൻസുലേറ്റഡ് ചെമ്പ് കേബിളുകൾ ഒരിക്കലും കത്തിക്കരുത്. PVC കത്തിക്കുന്നത് ക്യാൻസറിന് കാരണമാകുന്ന മാരകമായ ഡയോക്സിൻ വാതകം പുറപ്പെടുവിക്കുന്നു. കേബിളുകൾ ഉരിയാതെ നേരിട്ട് അംഗീകൃത റീസൈക്ലർക്ക് വിറ്റ് പൂർണ്ണ പണം നേടുക.'
    },
    {
      id: 'safe-02', title: 'Caution: Acid Leaching on Circuit Boards is Deadly',
      titleMr: 'सावधान: पीसीबी बोर्डवर ॲसिड / तेजाब वापरणे जीवघेणे आहे',
      titleHi: 'सावधान: पीसीबी पर एसिड का उपयोग जानलेवा है',
      titleTa: 'எச்சரிக்கை: சர்க்யூட் போர்டுகளில் அமில கசிவு கொல்லக்கூடியது',
      titleTe: 'జాగ్రత్త: సర్క్యూట్ బోర్డులపై యాసిడ్ లీచింగ్ ప్రాణాంతకం',
      titleKn: 'ಎಚ್ಚರಿಕೆ: ಸರ್ಕ್ಯೂಟ್ ಬೋರ್ಡ್‌ಗಳ ಮೇಲೆ ಆಮ್ಲ ಸೋರಿಕೆ ಮಾರಕ',
      titleMl: 'മുന്നറിയിപ്പ്: സർക്യൂട്ട് ബോർഡുകളിൽ ആസിഡ് ലീച്ചിംഗ് മാരകമാണ്',
      icon: '☠️🧪', color: '#b91c1c',
      hazard: 'Cyanide & Nitric Acid Gas Releases',
      hazardHi: 'साइनाइड और नाइट्रिक एसिड गैस का उत्सर्जन',
      hazardMr: 'सायनाइड आणि नायट्रिक ॲसिड वायूचे उत्सर्जन',
      hazardTa: 'சயனைடு மற்றும் நைட்ரிக் அமில வாயு வெளியேற்றம்',
      hazardTe: 'సైనైడ్ మరియు నైట్రిక్ యాసిడ్ వాయు విడుదల',
      hazardKn: 'ಸೈನೈಡ್ ಮತ್ತು ನೈಟ್ರಿಕ್ ಆಮ್ಲ ಅನಿಲ ಬಿಡುಗಡೆ',
      hazardMl: 'സയനൈഡ്, നൈട്രിക് ആസിഡ് വാതക പുറന്തള്ളൽ',
      healthRisk: 'Breathing acid fumes causes throat burns, blindness, and kidney failure. Informal acid pits only recover 20% of gold while losing expensive Palladium and Tantalum.',
      healthRiskHi: 'एसिड धुआं सांस में जाने से गले में जलन, अंधापन, और किडनी फेल हो सकती है। अनौपचारिक एसिड गड्ढे केवल 20% सोना निकाल पाते हैं जबकि महंगा पैलेडियम और टैंटलम बर्बाद हो जाता है।',
      healthRiskMr: 'ॲसिडचा धूर श्वासात गेल्यास घसा जळणे, अंधत्व, आणि किडनी निकामी होऊ शकते. अनधिकृत ॲसिड खड्डे फक्त २०% सोने काढतात आणि महाग पॅलेडियम व टँटॅलम वाया जाते.',
      healthRiskTa: 'அமில புகையை சுவாசிப்பது தொண்டை எரிச்சல், குருடு, மற்றும் சிறுநீரக செயலிழப்பை ஏற்படுத்தும். முறைசாரா அமில குழிகள் விலையுயர்ந்த பலேடியம் மற்றும் டான்டலம் இழந்து 20% தங்கத்தை மட்டுமே மீட்கும்.',
      healthRiskTe: 'యాసిడ్ పొగను పీల్చడం వల్ల గొంతు కాలిపోవడం, అంధత్వం, మరియు మూత్రపిండాల వైఫల్యం సంభవించవచ్చు. అనధికారిక యాసిడ్ గుంతలు ఖరీదైన పల్లాడియం మరియు టాంటాలమ్‌ను కోల్పోతూ కేవలం 20% బంగారాన్ని మాత్రమే రికవర్ చేస్తాయి.',
      healthRiskKn: 'ಆಮ್ಲದ ಹೊಗೆ ಉಸಿರಾಡುವುದರಿಂದ ಗಂಟಲು ಸುಡುವಿಕೆ, ಕುರುಡುತನ, ಮತ್ತು ಮೂತ್ರಪಿಂಡ ವೈಫಲ್ಯ ಉಂಟಾಗಬಹುದು. ಅನಧಿಕೃತ ಆಮ್ಲ ಗುಂಡಿಗಳು ದುಬಾರಿ ಪಲ್ಲಾಡಿಯಂ ಮತ್ತು ಟ್ಯಾಂಟಲಮ್ ಅನ್ನು ಕಳೆದುಕೊಂಡು ಕೇವಲ 20% ಚಿನ್ನವನ್ನು ಮಾತ್ರ ಮರುಪಡೆಯುತ್ತವೆ.',
      healthRiskMl: 'ആസിഡ് പുക ശ്വസിക്കുന്നത് തൊണ്ട പൊള്ളൽ, അന്ധത, വൃക്ക തകരാർ എന്നിവയ്ക്ക് കാരണമാകും. അനൗപചാരിക ആസിഡ് കുഴികൾ വിലയേറിയ പലേഡിയവും ടാന്റലവും നഷ്ടപ്പെടുത്തി വെറും 20% സ്വർണ്ണം മാത്രമേ വീണ്ടെടുക്കൂ.',
      safeMethod: 'Store motherboards in dry cartons and sell whole to CPCB units with computerized chemical extraction. You get paid for all 4 metals!',
      safeMethodHi: 'मदरबोर्ड को सूखे डिब्बों में रखें और कंप्यूटरीकृत रासायनिक निष्कर्षण वाली CPCB इकाइयों को पूरा बेचें। आपको सभी 4 धातुओं का पैसा मिलेगा!',
      safeMethodMr: 'मदरबोर्ड कोरड्या खोक्यांत ठेवा आणि संगणकीकृत रासायनिक प्रक्रिया असलेल्या CPCB युनिटला संपूर्ण विका. तुम्हाला सर्व ४ धातूंचे पैसे मिळतील!',
      safeMethodTa: 'மதர்போர்டுகளை உலர் பெட்டிகளில் சேமித்து, கணினிமயமாக்கப்பட்ட ரசாயன பிரித்தெடுப்புடன் கூடிய CPCB அலகுகளுக்கு முழுவதுமாக விற்கவும். நான்கு உலோகங்களுக்கும் பணம் கிடைக்கும்!',
      safeMethodTe: 'మదర్‌బోర్డులను పొడి పెట్టెల్లో నిల్వ చేసి, కంప్యూటరీకరించిన రసాయన వెలికితీతతో ఉన్న CPCB యూనిట్లకు పూర్తిగా అమ్మండి. మీకు అన్ని 4 లోహాలకు డబ్బు లభిస్తుంది!',
      safeMethodKn: 'ಮದರ್‌ಬೋರ್ಡ್‌ಗಳನ್ನು ಒಣ ಪೆಟ್ಟಿಗೆಗಳಲ್ಲಿ ಸಂಗ್ರಹಿಸಿ ಮತ್ತು ಕಂಪ್ಯೂಟರೀಕೃತ ರಾಸಾಯನಿಕ ಹೊರತೆಗೆಯುವಿಕೆ ಹೊಂದಿರುವ CPCB ಘಟಕಗಳಿಗೆ ಸಂಪೂರ್ಣವಾಗಿ ಮಾರಾಟ ಮಾಡಿ. ನಿಮಗೆ ಎಲ್ಲಾ 4 ಲೋಹಗಳಿಗೆ ಹಣ ಸಿಗುತ್ತದೆ!',
      safeMethodMl: 'മദർബോർഡുകൾ ഉണങ്ങിയ പെട്ടികളിൽ സൂക്ഷിച്ച് കമ്പ്യൂട്ടർവൽക്കരിച്ച രാസ വേർതിരിവുള്ള CPCB യൂണിറ്റുകൾക്ക് പൂർണ്ണമായി വിൽക്കുക. നാല് ലോഹങ്ങൾക്കും പണം ലഭിക്കും!',
      audioScriptEn: 'Backyard acid leaching destroys your lungs and recovers only tiny gold. Authorized recyclers extract Gold, Silver, Palladium and Copper cleanly and pay top rates.',
      audioScriptMr: 'तेजाब वापरल्याने डोळे आणि फुफ्फुसे जळतात. अधिकृत रिसायकलर्स आधुनिक मशिनने सोने, तांबे काढून जास्त पैसे देतात.',
      audioScriptHi: 'पीसीबी पर तेजाब डालने से जानलेवा गैस निकलती है। अधिकृत रीसायकलर आधुनिक मशीनों से धातु निकाल कर सबसे ऊंचा दाम देते हैं।',
      audioScriptTa: 'வீட்டுப்புற அமில கசிவு உங்கள் நுரையீரலை அழித்து சொற்ப தங்கத்தை மட்டுமே மீட்கும். அங்கீகரிக்கப்பட்ட மறுசுழற்சியாளர்கள் தங்கம், வெள்ளி, பலேடியம் மற்றும் தாமிரத்தை சுத்தமாக பிரித்தெடுத்து அதிக விலை தருவார்கள்.',
      audioScriptTe: 'ఇంటి వెనుక యాసిడ్ లీచింగ్ మీ ఊపిరితిత్తులను నాశనం చేసి కేవలం స్వల్ప బంగారాన్ని మాత్రమే రికవర్ చేస్తుంది. అధీకృత రీసైక్లర్లు బంగారం, వెండి, పల్లాడియం మరియు రాగిని శుభ్రంగా వెలికితీసి అత్యధిక ధరలు చెల్లిస్తారు.',
      audioScriptKn: 'ಮನೆಹಿಂದಿನ ಆಮ್ಲ ಸೋರಿಕೆ ನಿಮ್ಮ ಶ್ವಾಸಕೋಶವನ್ನು ನಾಶಪಡಿಸಿ ಅತ್ಯಲ್ಪ ಚಿನ್ನವನ್ನು ಮಾತ್ರ ಮರುಪಡೆಯುತ್ತದೆ. ಅಧಿಕೃತ ಮರುಬಳಕೆದಾರರು ಚಿನ್ನ, ಬೆಳ್ಳಿ, ಪಲ್ಲಾಡಿಯಂ ಮತ್ತು ತಾಮ್ರವನ್ನು ಶುದ್ಧವಾಗಿ ಹೊರತೆಗೆದು ಉತ್ತಮ ದರ ನೀಡುತ್ತಾರೆ.',
      audioScriptMl: 'വീട്ടുമുറ്റത്തെ ആസിഡ് ലീച്ചിംഗ് നിങ്ങളുടെ ശ്വാസകോശത്തെ നശിപ്പിക്കുകയും തുച്ഛമായ സ്വർണ്ണം മാത്രം വീണ്ടെടുക്കുകയും ചെയ്യുന്നു. അംഗീകൃത റീസൈക്ലർമാർ സ്വർണ്ണം, വെള്ളി, പലേഡിയം, ചെമ്പ് എന്നിവ ശുദ്ധമായി വേർതിരിച്ച് ഉയർന്ന വില നൽകുന്നു.'
    },
    {
      id: 'safe-03', title: 'Warning: Handle Lithium Batteries with Extreme Care',
      titleMr: 'चेतावणी: लिथियम बॅटऱ्यांना ठोकू किंवा दाबू नका',
      titleHi: 'चेतावनी: लिथियम बैटरी को कभी न फोड़ें या दबाएं',
      titleTa: 'எச்சரிக்கை: லித்தியம் பேட்டரிகளை மிகுந்த கவனத்துடன் கையாளவும்',
      titleTe: 'హెచ్చరిక: లిథియం బ్యాటరీలను అత్యంత జాగ్రత్తగా నిర్వహించండి',
      titleKn: 'ಎಚ್ಚರಿಕೆ: ಲಿಥಿಯಂ ಬ್ಯಾಟರಿಗಳನ್ನು ಅತ್ಯಂತ ಜಾಗರೂಕತೆಯಿಂದ ನಿರ್ವಹಿಸಿ',
      titleMl: 'മുന്നറിയിപ്പ്: ലിഥിയം ബാറ്ററികൾ അതീവ ജാഗ്രതയോടെ കൈകാര്യം ചെയ്യുക',
      icon: '💥🔋', color: '#ea580c',
      hazard: 'Thermal Runaway Explosion & Violent Fires',
      hazardHi: 'थर्मल रनअवे विस्फोट और भीषण आग',
      hazardMr: 'थर्मल रनअवे स्फोट आणि भीषण आग',
      hazardTa: 'வெப்ப ஓட்ட வெடிப்பு மற்றும் கடுமையான தீ',
      hazardTe: 'థర్మల్ రనావే పేలుడు మరియు తీవ్రమైన మంటలు',
      hazardKn: 'ಥರ್ಮಲ್ ರನ್‌ಅವೇ ಸ್ಫೋಟ ಮತ್ತು ತೀವ್ರ ಬೆಂಕಿ',
      hazardMl: 'താപ ഓട്ട സ്ഫോടനവും കടുത്ത തീപിടിത്തവും',
      healthRisk: 'Punctured or bent mobile batteries spontaneously ignite at 800°C and cannot be extinguished with water.',
      healthRiskHi: 'छेद वाली या मुड़ी हुई मोबाइल बैटरी 800°C पर अपने आप आग पकड़ लेती है और पानी से नहीं बुझाई जा सकती।',
      healthRiskMr: 'छिद्र पडलेली किंवा वाकलेली मोबाईल बॅटरी ८००°C तापमानाला आपोआप पेट घेते आणि पाण्याने विझवता येत नाही.',
      healthRiskTa: 'துளையிடப்பட்ட அல்லது வளைந்த மொபைல் பேட்டரிகள் 800°C இல் தானாகவே தீப்பற்றி எரியும், தண்ணீரால் அணைக்க முடியாது.',
      healthRiskTe: 'రంధ్రం చేయబడిన లేదా వంగిన మొబైల్ బ్యాటరీలు 800°C వద్ద తనంతట తానే మంటలు అంటుకుంటాయి మరియు నీటితో ఆర్పలేము.',
      healthRiskKn: 'ರಂಧ್ರವಾದ ಅಥವಾ ಬಾಗಿದ ಮೊಬೈಲ್ ಬ್ಯಾಟರಿಗಳು 800°C ನಲ್ಲಿ ತಾವಾಗಿಯೇ ಬೆಂಕಿ ಹತ್ತಿಕೊಳ್ಳುತ್ತವೆ ಮತ್ತು ನೀರಿನಿಂದ ನಂದಿಸಲಾಗುವುದಿಲ್ಲ.',
      healthRiskMl: 'ദ്വാരമുള്ളതോ വളഞ്ഞതോ ആയ മൊബൈൽ ബാറ്ററികൾ 800°C-ൽ സ്വയമേവ കത്തിപ്പിടിക്കുകയും വെള്ളം കൊണ്ട് അണയ്ക്കാൻ കഴിയാതിരിക്കുകയും ചെയ്യും.',
      safeMethod: 'Tape the metal terminals with cello tape, store in dry plastic buckets with sand, and keep away from iron scrap.',
      safeMethodHi: 'धातु के टर्मिनलों पर टेप लगाएं, रेत के साथ सूखी प्लास्टिक बाल्टियों में रखें, और लोहे के कबाड़ से दूर रखें।',
      safeMethodMr: 'धातूच्या टर्मिनल्सवर टेप लावा, वाळूसह कोरड्या प्लास्टिक बादलीत ठेवा, आणि लोखंडी भंगारापासून दूर ठेवा.',
      safeMethodTa: 'உலோக முனையங்களை டேப் ஒட்டவும், மணலுடன் உலர் பிளாஸ்டிக் வாளிகளில் சேமிக்கவும், இரும்பு பழைய இரும்பிலிருந்து விலகி வைக்கவும்.',
      safeMethodTe: 'లోహపు టెర్మినల్స్‌పై టేప్ వేయండి, ఇసుకతో పొడి ప్లాస్టిక్ బకెట్లలో నిల్వ చేయండి, మరియు ఇనుప స్క్రాప్ నుండి దూరంగా ఉంచండి.',
      safeMethodKn: 'ಲೋಹದ ಟರ್ಮಿನಲ್‌ಗಳಿಗೆ ಟೇಪ್ ಹಚ್ಚಿ, ಮರಳಿನೊಂದಿಗೆ ಒಣ ಪ್ಲಾಸ್ಟಿಕ್ ಬಕೆಟ್‌ಗಳಲ್ಲಿ ಸಂಗ್ರಹಿಸಿ, ಮತ್ತು ಕಬ್ಬಿಣದ ಸ್ಕ್ರ್ಯಾಪ್‌ನಿಂದ ದೂರವಿಡಿ.',
      safeMethodMl: 'ലോഹ ടെർമിനലുകളിൽ ടേപ്പ് ഒട്ടിക്കുക, മണലോടെ ഉണങ്ങിയ പ്ലാസ്റ്റിക് ബക്കറ്റുകളിൽ സൂക്ഷിക്കുക, ഇരുമ്പ് സ്ക്രാപ്പിൽ നിന്ന് അകലെ വയ്ക്കുക.',
      audioScriptEn: 'Do not hammer or puncture lithium batteries. They can explode into violent fires. Tape the terminals and store them in dry buckets.',
      audioScriptMr: 'मोबाईल किंवा लॅपटॉपच्या बॅटऱ्यांना हातोड्याने ठोकू नका. ते अचानक पेट घेऊ शकतात. त्यांना कोरड्या बादलीत वाळूमध्ये ठेवा.',
      audioScriptHi: 'लिथियम बैटरी पर हथौड़ा न चलाएं। इनमें 800 डिग्री का भयानक विस्फोट हो सकता है। इन्हें अलग प्लास्टिक बाल्टी में रखें।',
      audioScriptTa: 'லித்தியம் பேட்டரிகளை சுத்தியலால் அடிக்கவோ துளையிடவோ வேண்டாம். அவை கடுமையான தீயாக வெடிக்கலாம். முனையங்களை டேப் ஒட்டி உலர் வாளிகளில் சேமிக்கவும்.',
      audioScriptTe: 'లిథియం బ్యాటరీలను సుత్తితో కొట్టవద్దు లేదా రంధ్రం చేయవద్దు. అవి తీవ్రమైన మంటలుగా పేలవచ్చు. టెర్మినల్స్‌పై టేప్ వేసి పొడి బకెట్లలో నిల్వ చేయండి.',
      audioScriptKn: 'ಲಿಥಿಯಂ ಬ್ಯಾಟರಿಗಳನ್ನು ಸುತ್ತಿಗೆಯಿಂದ ಹೊಡೆಯಬೇಡಿ ಅಥವಾ ಚುಚ್ಚಬೇಡಿ. ಅವು ತೀವ್ರ ಬೆಂಕಿಯಾಗಿ ಸ್ಫೋಟಿಸಬಹುದು. ಟರ್ಮಿನಲ್‌ಗಳಿಗೆ ಟೇಪ್ ಹಚ್ಚಿ ಒಣ ಬಕೆಟ್‌ಗಳಲ್ಲಿ ಸಂಗ್ರಹಿಸಿ.',
      audioScriptMl: 'ലിഥിയം ബാറ്ററികളെ ചുറ്റികകൊണ്ട് അടിക്കുകയോ തുളയ്ക്കുകയോ ചെയ്യരുത്. അവ കടുത്ത തീപിടിത്തമായി പൊട്ടിത്തെറിക്കാം. ടെർമിനലുകളിൽ ടേപ്പ് ഒട്ടിച്ച് ഉണങ്ങിയ ബക്കറ്റുകളിൽ സൂക്ഷിക്കുക.'
    },
    {
      id: 'safe-04', title: 'Safety: CRT Monitors Vacuum Implosion Hazard',
      titleMr: 'सुरक्षा: जुन्या सीआरटी टीव्हीवर हातोडा मारू नका',
      titleHi: 'सुरक्षा: पुराने सीआरटी मॉनिटर को पटक कर न तोड़ें',
      titleTa: 'பாதுகாப்பு: சிஆர்டி மானிட்டர்கள் வெற்றிட வெடிப்பு ஆபத்து',
      titleTe: 'భద్రత: సిఆర్టి మానిటర్ల వాక్యూమ్ ఇంప్లోషన్ ప్రమాదం',
      titleKn: 'ಸುರಕ್ಷತೆ: ಸಿಆರ್‌ಟಿ ಮಾನಿಟರ್‌ಗಳ ವ್ಯಾಕ್ಯೂಮ್ ಇಂಪ್ಲೋಷನ್ ಅಪಾಯ',
      titleMl: 'സുരക്ഷ: സിആർടി മോണിറ്ററുകളുടെ വാക്വം ഇംപ്ലോഷൻ അപകടം',
      icon: '🛡️📺', color: '#d97706',
      hazard: 'Glass Shrapnel & Leaded Toxic Phosphor Powder',
      hazardHi: 'कांच के टुकड़े और सीसायुक्त जहरीला फॉस्फोर पाउडर',
      hazardMr: 'काचेचे तुकडे आणि शिशायुक्त विषारी फॉस्फर पावडर',
      hazardTa: 'கண்ணாடி துண்டுகள் மற்றும் ஈயம் கலந்த நச்சு பாஸ்பர் தூள்',
      hazardTe: 'గాజు పెంకులు మరియు సీసంతో కూడిన విషపూరిత ఫాస్ఫర్ పొడి',
      hazardKn: 'ಗಾಜಿನ ಚೂರುಗಳು ಮತ್ತು ಸೀಸ ಮಿಶ್ರಿತ ವಿಷಕಾರಿ ಫಾಸ್ಫರ್ ಪುಡಿ',
      hazardMl: 'ഗ്ലാസ് ചീളുകളും ഈയം കലർന്ന വിഷലിപ്ത ഫോസ്ഫർ പൊടിയും',
      healthRisk: 'Smashed CRT tubes implode with huge force, shooting glass shards and toxic barium/lead dust into eyes and lungs.',
      healthRiskHi: 'टूटी हुई सीआरटी ट्यूब भारी बल के साथ अंदर की ओर फटती हैं, जिससे कांच के टुकड़े और जहरीली बेरियम/सीसा धूल आंखों व फेफड़ों में जाती है।',
      healthRiskMr: 'फुटलेल्या सीआरटी नळ्या प्रचंड ताकदीने आतल्या बाजूने फुटतात, त्यामुळे काचेचे तुकडे आणि विषारी बेरियम/शिसे धूळ डोळ्यांत व फुफ्फुसांत जाते.',
      healthRiskTa: 'உடைந்த சிஆர்டி குழாய்கள் பெரும் சக்தியுடன் உள்நோக்கி வெடித்து, கண்ணாடி துண்டுகளையும் நச்சு பேரியம்/ஈய தூசியையும் கண்கள் மற்றும் நுரையீரலுக்குள் செலுத்தும்.',
      healthRiskTe: 'పగిలిన సిఆర్టి ట్యూబులు అపారమైన శక్తితో లోపలికి పేలిపోయి, గాజు పెంకులు మరియు విషపూరిత బేరియం/సీసం దుమ్మును కళ్ళలోకి మరియు ఊపిరితిత్తుల్లోకి పంపుతాయి.',
      healthRiskKn: 'ಒಡೆದ ಸಿಆರ್‌ಟಿ ಟ್ಯೂಬ್‌ಗಳು ಅಗಾಧ ಶಕ್ತಿಯಿಂದ ಒಳಮುಖವಾಗಿ ಸ್ಫೋಟಗೊಂಡು, ಗಾಜಿನ ಚೂರುಗಳು ಮತ್ತು ವಿಷಕಾರಿ ಬೇರಿಯಂ/ಸೀಸ ಧೂಳನ್ನು ಕಣ್ಣುಗಳಿಗೆ ಮತ್ತು ಶ್ವಾಸಕೋಶಗಳಿಗೆ ಚಿಮ್ಮಿಸುತ್ತವೆ.',
      healthRiskMl: 'തകർന്ന സിആർടി ട്യൂബുകൾ വൻ ശക്തിയോടെ അകത്തേക്ക് പൊട്ടിത്തെറിച്ച്, ഗ്ലാസ് ചീളുകളും വിഷലിപ്ത ബേരിയം/ഈയ പൊടിയും കണ്ണുകളിലേക്കും ശ്വാസകോശത്തിലേക്കും തെറിപ്പിക്കും.',
      safeMethod: 'Keep the glass tube unbroken. Authorized recyclers have specialized negative-pressure diamond cutters to extract leaded glass safely.',
      safeMethodHi: 'कांच की ट्यूब को बिना तोड़े रखें। अधिकृत रीसायकलरों के पास सीसायुक्त कांच को सुरक्षित रूप से निकालने के लिए विशेष नेगेटिव-प्रेशर डायमंड कटर होते हैं।',
      safeMethodMr: 'काचेची नळी न फोडता ठेवा. अधिकृत रिसायकलर्सकडे शिसेयुक्त काच सुरक्षितपणे काढण्यासाठी खास निगेटिव्ह-प्रेशर डायमंड कटर असतात.',
      safeMethodTa: 'கண்ணாடி குழாயை உடைக்காமல் வைக்கவும். அங்கீகரிக்கப்பட்ட மறுசுழற்சியாளர்களிடம் ஈயம் கலந்த கண்ணாடியை பாதுகாப்பாக பிரித்தெடுக்க சிறப்பு நெகடிவ்-பிரஷர் டைமண்ட் கட்டர்கள் உள்ளன.',
      safeMethodTe: 'గాజు ట్యూబును పగలకుండా ఉంచండి. అధీకృత రీసైక్లర్ల వద్ద సీసంతో కూడిన గాజును సురక్షితంగా వెలికితీసేందుకు ప్రత్యేక నెగటివ్-ప్రెజర్ డైమండ్ కట్టర్లు ఉన్నాయి.',
      safeMethodKn: 'ಗಾಜಿನ ಟ್ಯೂಬ್ ಅನ್ನು ಒಡೆಯದೆ ಇಡಿ. ಅಧಿಕೃತ ಮರುಬಳಕೆದಾರರು ಸೀಸ ಮಿಶ್ರಿತ ಗಾಜನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಹೊರತೆಗೆಯಲು ವಿಶೇಷ ನೆಗೆಟಿವ್-ಪ್ರೆಶರ್ ಡೈಮಂಡ್ ಕಟ್ಟರ್‌ಗಳನ್ನು ಹೊಂದಿದ್ದಾರೆ.',
      safeMethodMl: 'ഗ്ലാസ് ട്യൂബ് പൊട്ടിക്കാതെ സൂക്ഷിക്കുക. ഈയം കലർന്ന ഗ്ലാസ് സുരക്ഷിതമായി വേർതിരിക്കാൻ അംഗീകൃത റീസൈക്ലർമാർക്ക് പ്രത്യേക നെഗറ്റീവ്-പ്രഷർ ഡയമണ്ട് കട്ടറുകൾ ഉണ്ട്.',
      audioScriptEn: 'Do not break CRT tubes with hammers. Smashed tubes blast high-speed glass shards and toxic lead dust. Deliver unbroken for full value.',
      audioScriptMr: 'सीआरटी टीव्ही फोडल्याने काचेचे तुकडे उडतात आणि शिशाची विषारी धूळ फुफ्फुसात जाते. काच अखंड ठेवून विका.',
      audioScriptHi: 'सीआरटी टीवी को कभी पत्थर या हथौड़े से न तोड़ें। शीशा फूटने से आंखों में कांच लग सकता है। इसे साबुत ही बेचें।',
      audioScriptTa: 'சிஆர்டி குழாய்களை சுத்தியலால் உடைக்காதீர்கள். உடைந்த குழாய்கள் அதிவேக கண்ணாடி துண்டுகளையும் நச்சு ஈயத் தூசியையும் வெடிக்கச் செய்யும். முழு மதிப்புக்காக உடைக்காமல் ஒப்படைக்கவும்.',
      audioScriptTe: 'సిఆర్టి ట్యూబులను సుత్తులతో పగలగొట్టవద్దు. పగిలిన ట్యూబులు అధిక వేగంతో గాజు పెంకులను మరియు విషపూరిత సీస దుమ్మును పేల్చివేస్తాయి. పూర్తి విలువ కోసం పగలకుండా అప్పగించండి.',
      audioScriptKn: 'ಸಿಆರ್‌ಟಿ ಟ್ಯೂಬ್‌ಗಳನ್ನು ಸುತ್ತಿಗೆಯಿಂದ ಒಡೆಯಬೇಡಿ. ಒಡೆದ ಟ್ಯೂಬ್‌ಗಳು ಅತಿವೇಗದ ಗಾಜಿನ ಚೂರುಗಳನ್ನು ಮತ್ತು ವಿಷಕಾರಿ ಸೀಸದ ಧೂಳನ್ನು ಸ್ಫೋಟಿಸುತ್ತವೆ. ಪೂರ್ಣ ಮೌಲ್ಯಕ್ಕಾಗಿ ಒಡೆಯದೆ ತಲುಪಿಸಿ.',
      audioScriptMl: 'സിആർടി ട്യൂബുകൾ ചുറ്റികകൊണ്ട് പൊട്ടിക്കരുത്. തകർന്ന ട്യൂബുകൾ അതിവേഗ ഗ്ലാസ് ചീളുകളും വിഷലിപ്ത ഈയ പൊടിയും പൊട്ടിത്തെറിപ്പിക്കും. പൂർണ്ണ മൂല്യത്തിനായി പൊട്ടിക്കാതെ കൈമാറുക.'
    }
  ]
};

module.exports = SEED_DATA;
